# permissions for end users to view daemonservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: daemonservice-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: security-operator
    app.kubernetes.io/part-of: security-operator
    app.kubernetes.io/managed-by: kustomize
  name: daemonservice-viewer-role
rules:
- apiGroups:
  - monitoring.example.com
  resources:
  - daemonservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.example.com
  resources:
  - daemonservices/status
  verbs:
  - get
