# permissions for end users to edit monitoringservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: monitoringservice-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: security-operator
    app.kubernetes.io/part-of: security-operator
    app.kubernetes.io/managed-by: kustomize
  name: monitoringservice-editor-role
rules:
- apiGroups:
  - monitoring.neridio.com
  resources:
  - monitoringservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.neridio.com
  resources:
  - monitoringservices/status
  verbs:
  - get
