---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - mygroup.example.com
  resources:
  - securitypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mygroup.example.com
  resources:
  - securitypolicies/finalizers
  verbs:
  - update
- apiGroups:
  - mygroup.example.com
  resources:
  - securitypolicies/status
  verbs:
  - get
  - patch
  - update
