# permissions for end users to edit securitypolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: securitypolicy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: security-operator
    app.kubernetes.io/part-of: security-operator
    app.kubernetes.io/managed-by: kustomize
  name: securitypolicy-editor-role
rules:
- apiGroups:
  - mygroup.example.com
  resources:
  - securitypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mygroup.example.com
  resources:
  - securitypolicies/status
  verbs:
  - get
