apiVersion: monitoring.mydomain.com/v1alpha1
kind: HealthCheck
metadata:
  labels:
    app.kubernetes.io/name: healthcheck
    app.kubernetes.io/instance: healthcheck-sample
    app.kubernetes.io/part-of: security-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: security-operator
  name: healthcheck-sample
spec:
  # TODO(user): Add fields here
  scheduler: true
  controller: true
