//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigDriftSpec) DeepCopyInto(out *ConfigDriftSpec) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigDriftSpec.
func (in *ConfigDriftSpec) DeepCopy() *ConfigDriftSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigDriftSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigDriftStatus) DeepCopyInto(out *ConfigDriftStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigDriftStatus.
func (in *ConfigDriftStatus) DeepCopy() *ConfigDriftStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigDriftStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sConfigDriftSpec) DeepCopyInto(out *K8sConfigDriftSpec) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sConfigDriftSpec.
func (in *K8sConfigDriftSpec) DeepCopy() *K8sConfigDriftSpec {
	if in == nil {
		return nil
	}
	out := new(K8sConfigDriftSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sConfigDriftStatus) DeepCopyInto(out *K8sConfigDriftStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sConfigDriftStatus.
func (in *K8sConfigDriftStatus) DeepCopy() *K8sConfigDriftStatus {
	if in == nil {
		return nil
	}
	out := new(K8sConfigDriftStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sMonitorSpec) DeepCopyInto(out *K8sMonitorSpec) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sMonitorSpec.
func (in *K8sMonitorSpec) DeepCopy() *K8sMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(K8sMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K8sMonitorStatus) DeepCopyInto(out *K8sMonitorStatus) {
	*out = *in
	if in.ServicesStatus != nil {
		in, out := &in.ServicesStatus, &out.ServicesStatus
		*out = make([]ServiceStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K8sMonitorStatus.
func (in *K8sMonitorStatus) DeepCopy() *K8sMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(K8sMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringService) DeepCopyInto(out *MonitoringService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringService.
func (in *MonitoringService) DeepCopy() *MonitoringService {
	if in == nil {
		return nil
	}
	out := new(MonitoringService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonitoringService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringServiceList) DeepCopyInto(out *MonitoringServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MonitoringService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringServiceList.
func (in *MonitoringServiceList) DeepCopy() *MonitoringServiceList {
	if in == nil {
		return nil
	}
	out := new(MonitoringServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MonitoringServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringServiceSpec) DeepCopyInto(out *MonitoringServiceSpec) {
	*out = *in
	in.ConfigDrift.DeepCopyInto(&out.ConfigDrift)
	out.Velero = in.Velero
	in.K8sMonitor.DeepCopyInto(&out.K8sMonitor)
	in.K8sConfigDrift.DeepCopyInto(&out.K8sConfigDrift)
	in.NodeServiceMonitor.DeepCopyInto(&out.NodeServiceMonitor)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringServiceSpec.
func (in *MonitoringServiceSpec) DeepCopy() *MonitoringServiceSpec {
	if in == nil {
		return nil
	}
	out := new(MonitoringServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MonitoringServiceStatus) DeepCopyInto(out *MonitoringServiceStatus) {
	*out = *in
	out.ConfigDriftStatus = in.ConfigDriftStatus
	out.VeleroStatus = in.VeleroStatus
	if in.K8sMonitorStatus != nil {
		in, out := &in.K8sMonitorStatus, &out.K8sMonitorStatus
		*out = make([]K8sMonitorStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.K8sConfigDriftStatus != nil {
		in, out := &in.K8sConfigDriftStatus, &out.K8sConfigDriftStatus
		*out = make([]K8sConfigDriftStatus, len(*in))
		copy(*out, *in)
	}
	if in.NodeServiceMonitorStatus != nil {
		in, out := &in.NodeServiceMonitorStatus, &out.NodeServiceMonitorStatus
		*out = make([]NodeServiceMonitorStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MonitoringServiceStatus.
func (in *MonitoringServiceStatus) DeepCopy() *MonitoringServiceStatus {
	if in == nil {
		return nil
	}
	out := new(MonitoringServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeServiceMonitorSpec) DeepCopyInto(out *NodeServiceMonitorSpec) {
	*out = *in
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeServiceMonitorSpec.
func (in *NodeServiceMonitorSpec) DeepCopy() *NodeServiceMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(NodeServiceMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeServiceMonitorStatus) DeepCopyInto(out *NodeServiceMonitorStatus) {
	*out = *in
	if in.ServicesStatus != nil {
		in, out := &in.ServicesStatus, &out.ServicesStatus
		*out = make([]ServiceStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeServiceMonitorStatus.
func (in *NodeServiceMonitorStatus) DeepCopy() *NodeServiceMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(NodeServiceMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceStatus) DeepCopyInto(out *ServiceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStatus.
func (in *ServiceStatus) DeepCopy() *ServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroSpec) DeepCopyInto(out *VeleroSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroSpec.
func (in *VeleroSpec) DeepCopy() *VeleroSpec {
	if in == nil {
		return nil
	}
	out := new(VeleroSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroStatus) DeepCopyInto(out *VeleroStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroStatus.
func (in *VeleroStatus) DeepCopy() *VeleroStatus {
	if in == nil {
		return nil
	}
	out := new(VeleroStatus)
	in.DeepCopyInto(out)
	return out
}
